import { Fragment } from 'react'
import { rupees } from '../utils/actions'
import ServiceEstimator from '../components/ServiceEstimator'
import CaseChecks from '../components/CaseChecks'
import { screenWarranty } from '../utils/warranty'
export default function WarrantyPage({ filtered, visible, showAll, setShowAll, filter, setFilter, status, cases, assets, assessments, retry, onLink, filterVehicle, setFilterVehicle }) {
  const attention = cases.filter((c) => screenWarranty(c, assets, cases).state !== 'Ready for review').length
  return <div className="page-stack"><article className="panel panel-large" id="warranty"><div className="panel-header"><div><p className="eyebrow accent">Automatic warranty screening</p><h3>Claim queue ({filtered.length})</h3></div><div className="hero-actions"><button className="ghost-button small" onClick={retry}>Retry model checks</button><button className="ghost-button small" onClick={() => setShowAll(!showAll)}>{showAll ? 'Show first 4' : 'View all'}</button></div></div><p className="subcopy">{attention} cases need policy details or attention. Checks re-run when linked policy or financing records change. Open each case for reasons; final decisions are recorded below.</p><label className="queue-filter">Vehicle<select value={filterVehicle} onChange={(e) => setFilterVehicle(e.target.value)}><option value="">All vehicles</option>{assets.map((a) => <option key={a.id} value={a.id}>{a.registration} · {a.owner}</option>)}</select></label><label className="queue-filter">Decision status<select value={filter} onChange={(e) => setFilter(e.target.value)}>{['All', 'Pending', 'Review', 'Approved', 'Rejected'].map((s) => <option key={s}>{s}</option>)}</select></label><div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Owner</th><th>Component</th><th>Staff decision</th><th>Amount</th></tr></thead><tbody>{visible.map((c) => <Fragment key={c.id}><tr><td>{c.vehicle}</td><td>{c.owner}</td><td>{c.claim}</td><td><select aria-label={`Status for ${c.owner}`} value={c.status} onChange={(e) => status(c.id, e.target.value)}>{['Pending', 'Review', 'Approved', 'Rejected'].map((s) => <option key={s}>{s}</option>)}</select></td><td>{rupees(c.amount)}</td></tr><tr><td colSpan="5"><CaseChecks item={c} assets={assets} cases={cases} model={assessments[c.id]} onLink={onLink} /></td></tr></Fragment>)}</tbody></table></div>{!visible.length && <p className="empty-state">No matching cases. Register a vehicle in Financing, then create a New case.</p>}</article><ServiceEstimator /></div>
}
